### ISSUE TITLE
运行url-extract 中examples中例子时报错 

### ISSUE THREAD

**Issue by yangyu102198** [miniflycn/url-extract#13]
node的版本是v4.2.2， 系统是window7
phantomjs 版本是1.9.8
执行测试例子的时候报如下错误：

event.js:141
         throw er;// Unhandled 'error' event

Error: spawn phantomjs ENOENT
        at exports._errnoException(util.js:874:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
        at onErrorNT(internal/child_process.js:344:16)
        at doNTCallback2 (node.js:441:9)
        at process._tickCallback (node.js:355:17)
        at Function.Module.runMain (module.js:469:11)
        at startup (node.js:136:18)
        at node.js:963:3

**Comment by miniflycn** [comment]
= =4.0.我试试

**Comment by miniflycn** [comment]
你跑的是哪个例子啊？好像我没问题哦

**Comment by yangyu102198** [comment]
// 初始化
var ue = require('url-extract')();
// 截图并保存在 ./snapshot/nodejs.png
ue.snapshot('http://www.nodejs.org', './snaphost/nodejs.png');

这个例子

**Comment by yangyu102198** [comment]
test.js

内容为
// 初始化
var ue = require('url-extract')();
// 截图并保存在 ./snapshot/nodejs.png
ue.snapshot('http://www.nodejs.org', './snaphost/nodejs.png');

运行
node test.js 

一直报上面的错

**Comment by miniflycn** [comment]
我试了下还是没问题，请检查两件事情：
1. CMD有没有phantomjs命令，没有可能是Phantomjs安装有问题，或者配置环境变量
2. 检查网络有没有问题
